### PR TITLE
implement changes that make the project compatible with sphinx >= 1.8.5

### PR DESCRIPTION
**Pull request by mherkazandjian**
related issues #26 #24

### CODE REVIEW

**Comment by mherkazandjian** [comment]
the following example https://github.com/mherkazandjian/docxsphinx/tree/mher/sphinx-dep-upgrade/examples/sample_6
has a ``'`` in the title that is causing the docx build to fail. To reproduce the error:

````bash
cd docxsphinx/examples/sample_6
PYTHONPATH=../../src sphinx-build -b docx source build 
````

the following error is displayed in the traceback

````bash
    logger.info(' '.join([_func, text]))
Message: 'add_text {\'text\': "\'Welcome to Python\u2019s docx module\'"}'
````
the problem is with the

````#\u2019s#```` part where the ``'`` is treated as a unicode

**Comment by mherkazandjian** [comment]
with 18c7ce5 all the tests pass but there is still the unicode related error in examples/sample_6

````text
    logger.info(' '.join([_func, text]))                                               
Message: 'depart_Text {\'node\': "<#text: \'Welcome to Python\u2019s docx module\'>"}'
Arguments: ()                
````
this problem does not exist in ``sample_5``

**Comment by mherkazandjian** [comment]
although now with the latest version of sphinx and docutils there is an error, the docx is rendered e.g in sample_6

image

**Comment by hugobuddel** [comment]
This works well for me, so merging!

**Pull request merged**
